import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import RandomFox from '../components/RandomFox';

const inter = Inter({ subsets: ['latin'] });
const random = (): number => Math.floor(Math.random() * 123) + 1;

const Home: NextPage = () => {
  const [images, setImages] = useState<string[]>([
    `https://randomfox.ca/images/${random()}.jpg`,
    `https://randomfox.ca/images/${random()}.jpg`,
    `https://randomfox.ca/images/${random()}.jpg`,
    `https://randomfox.ca/images/${random()}.jpg`,
  ]);

  return (
    <>
      <Head>
        <title>Esparev</title>
        <meta name='description' content='Generated by Esparev' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-3xl font-bold underline'>Hello, World</h1>
        {images.map((image, index) => (
          <div key={index} className='p-4'>
            <RandomFox image={image} />
          </div>
        ))}
      </main>
    </>
  );
};
export default Home;
